name: news_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluent_ui: ^4.0.3
  window_manager: ^0.2.7
  transparent_image: ^2.0.0
  timeago: ^3.2.2
  http: ^0.13.4
  url_launcher: ^6.0.20
  share_plus: ^4.0.4
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  
